name: Desktop App Build (without signing)

on:
  pull_request:
    branches:
      - v1.0
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle-desktop:
    uses: ./.github/workflows/bundle-desktop.yml
    with:
      signing: false
