on:
  push:
    tags:
      - "v00.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

name: Release CLI

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        architecture: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            suffix: unknown-linux-gnu
          - os: macos-latest
            suffix: apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.architecture }}-${{ matrix.suffix }}
          override: true

      - name: Install dependencies for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
          if [ "${{ matrix.architecture }}" == "aarch64" ]; then
            sudo dpkg --add-architecture arm64
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu libssl-dev:arm64 libc6-dev-arm64-cross
          fi

      - name: Build the project
        shell: bash
        run: |
          export TARGET=${{ matrix.architecture }}-${{ matrix.suffix }}
          cargo build --release --target $TARGET
          mkdir -p dist
          cp target/${TARGET}/release/goose dist/
          cp target/${TARGET}/release/goosed dist/
          tar -cjf dist/goose-${TARGET}.tar.bz2 -C dist goose goosed
          echo "dist/goose-${TARGET}.tar.bz2" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: goose-${{ matrix.architecture }}-${{ matrix.suffix }}
          path: dist/goose-${{ matrix.architecture }}-${{ matrix.suffix }}.tar.bz2

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          merge: true

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "goose-*.tar.bz2"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: true
