name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to main
      - ldelalande/fix-docs-workflow  # TODO: Remove this line
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy_docs.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv install

    - name: Build the documentation
      run: uv run mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
